### PR TITLE
Golden Drought: DTW

### PR DESCRIPTION
**Pull request by Crnsxx**
Golden Drought: DTW

### CODE REVIEW

**Comment by DeternoMC** [comment]
"By Reshif and Thrasilias"

damn credit stealers

**Comment by tjhubz** [comment]
Please comment with images of the map

**Comment by master00ofdsiware** [comment]
There's no need to have this. The map is fine as CTW; don't make it worse by converting it to DTW.

**Comment by scorpion808** [comment]
The CTW version map isn't going anywhere. If people don't like this version of the map then they can always downvote it on discord. People can add any maps they want. Just because you hate DTW doesn't mean that there is no need to have this map.

**Comment by master00ofdsiware** [comment]
It's more acceptable if the CTW one is kept. It shouldn't be like Rooted where the inferior DTW edit is the only version on the server.

**Comment by BennyDoesTheStuff** [comment]
Doesn't seem like a CTW version of this map would work well on the server based on the comments. Next time you submit a map, make sure you post some pictures of it as a reference to what the map looks like.

**Pull request closed without merging**
