### PR TITLE
Transpo - Warzone DTW Map

### PR DESCRIPTION
**Pull request by DevGapple**
## Transpo - DevGapple
One of the first Pixel Art maps made for Warzone

### Details
Name: Transpo
Gamemode: DTW
Recommended Players: 3 to 15 (per team)
Wool Count: 1 for each team
Attack Score: 7/10 -- Pretty Easy
Defense Score: 8/10 -- Wool is seperated from spawn by two short islands.
Average Length: 5 - 10 min
Normal Length: 5 - 10 min

### Description
A medium sized map that includes perfectly ratioed 3D pixel art. Most all islands are some form of transportation in minecraft. The wools can be found on opposite corners and are colored versions of gold/iron nuggets. Features include multiple push lanes, loot chests, floating gravel, and a Elytra spectator/initial spawn island.

### Pictures
image
image
image
image
image
image
image
**Overhead:**
image

### Credits
I give credit to OD1-ByHL for creating the [initial pull request](https://github.com/WarzoneMC/Maps/pull/106), pruning the map, and writing the description. Thanks.

### CODE REVIEW

**Comment by JapaneseSquid** [comment]
there’s an old OCN map called blocks DTM 
And it’s pixel art

**Comment by DevGapple** [comment]
Oh, ok I'll change that real fast.

**Comment by Thrasilias** [comment]
@DevGapple updated ur map.json (no hate) https://hastebin.com/winebopape.json

**Comment by Thrasilias** [comment]
There: https://hastebin.com/ezidekiyar.json

**Comment by DevGapple** [comment]
Ok.. ty lemme know @Thrasilias if you see any other errors,

**Comment by TRose2000** [comment]
Reeeee oktybai p.s HAPPY NEW YEAR

**Pull request merged**
