### PR TITLE
fix up quintus (enchantments and fish)

### PR DESCRIPTION
**Pull request by ThatOneTqnk**

### CODE REVIEW

**Comment by Owehttamy** [comment]
Unless the map hasn't actually been updated, none of these additions worked.

**Comment by ThatOneTqnk** [comment]
has been tested so it does work

**Comment by Owehttamy** [comment]
I have evidence on my stream on Warzone that shows it wasn't working. I'm not going to have another nonsensical arguement about something that doesn't truly matter anyways. All I'm doing is saying after playing on the map two days from the fix being merged I didn't see the fix implemented.

I'm trying to help and from what I can tell the tone of your response wasn't very necessary. Even if the map hasn't been updated, this could just be taken as a light reminder to update it. There's no reason to get defensive about it. *I never said your coding didn't work*

**Comment by ThatOneTqnk** [comment]
not arguing lol, just stating that i tested it so it works?

**Comment by jorgeberrex** [comment]
@Owehttamy don't rely just on the production server to draw conclusions since the plugin JAR file and maps repository get updated only once a week. I'm saying this because you've already reported a few bugs that had already been solved (and had been brought to your attention) but are just not live in production yet. There's a test server where everything gets tested before going into production.

**Comment by Owehttamy** [comment]
"Instead of *assuming* <that the problem's not been fixed>, you could also *check yourself* by *spinning up*..."

Note that you used the phrase "spinning up," which is typically used when you do something with ease or without effort. Then going to "check yourself," this can be assumed from the previous statement that I could've checked something hasitly without ease rather than make a comment about your work.

Whether or not you're trying to create an arguement, your wording and sentence structure provide a differing tone from your intentions.

Note that this isn't meant to be aggressive but is just to give some constructive criticism to make sure in a future case someone else doesn't misinterprete your tone as it can be easy to assume with purely text. :^)

**Comment by ThatOneTqnk** [comment]
ok just to clarify i use the phrase "spinning up" since that is a common phrase associated with creating a server

**Comment by jellz** [comment]
[Definition](https://en.wiktionary.org/wiki/spin_up)

**Pull request merged**
