### PR TITLE
Add Bridges

### PR DESCRIPTION
**Pull request by Nightsent**
:)

### CODE REVIEW

**Comment by DeternoMC** [comment]
you need to add a screenshot

**Comment by Nightsent** [comment]
;-; how do I do that
(Only took me like 2 1/2 hours to do this pr thing dont worry)

**Comment by Nightsent** [comment]
There um good enough. Idk how to edit it.. https://imgur.com/gallery/eVDtt

**Comment by DeternoMC** [comment]
Nightsent, just drag each imagine from your computer (lets say desktop) to a github comment. As you can see when you're writing a comment, theres a blue line like - - - - -, and underneath it, it says "Attach files by dragging & dropping, selecting them, or pasting from the clipbord".

**Pull request merged**
