### PR TITLE
Kill Streaks 

### PR DESCRIPTION
**Pull request by zStorMaus**
Kill Streaks added to Fracture and Midnight Train, 1 golden apple per kill.
Edit: Added Kill rewards to Orion. 1 golden apple

### CODE REVIEW

**Comment by jorgeberrex** [comment]
While those work, I recommend editing them to use the new killstreak actions feature

**Comment by CrazyisCreeps** [comment]
How does the new kill streak actions feature work? Can you provide any sort of documentation?

**Comment by jorgeberrex** [comment]
The documentation has been already updated for it https://docs.warz.one/#/killstreaks

**Comment by CrazyisCreeps** [comment]
Good to know, thanks for linking. I'll be sure to use this from now on.

**Pull request merged**
