### PR TITLE
Nuketown (Infection) and Crossfire (Blitz) Add

### PR DESCRIPTION
**Pull request by Bearinx**
Dont worry about the deletes and adds just the create nuketown is what I did the rest were mess ups

### CODE REVIEW

**Comment by tjhubz** [comment]
Pictures please

**Comment by Bearinx** [comment]
Images added

**Comment by tjhubz** [comment]
Images in comment not map files

**Comment by Palmidence** [comment]
This version of Nuketown seems very... boring. Do you have a version that has more detail, or isn't so flat and open?

**Comment by DeternoMC** [comment]
@Palmidence, Not sure what version of nuketown you have seen, but nuketown is quite fine, (all the flat parts on the outside you cannot get to, just the actual nuketown map is available to play. However, there are plenty spots that you could get to!

**Comment by Bearinx** [comment]
GORSH CAN I HAVE PIZZA NOW I AM STARVING!

**Comment by Palmidence** [comment]
You should make separate PRs for separate maps

**Pull request closed without merging**
