### PR TITLE
Changed some things (Stonehenge DTW map)

### PR DESCRIPTION
**Pull request by Crnsxx**
Added:
  - Regions (Red-Team, Blue-Team) [No Longer spawnkill / killfarming]
  - Iron Pickaxe

### CODE REVIEW

**Comment by DeternoMC** [comment]
I don't agree with there being a pickaxe. It's made that way so people cant just mine under the wool.

**Comment by Thrasilias** [comment]
They can't mine under the wool

**Comment by Palmidence** [comment]
What is stopping them from mining under the wool? @Thrasilias

**Comment by Thrasilias** [comment]
@Palmidence wasnt there Bedrock under the Objective?

**Pull request closed without merging**
