### PR TITLE
Increase health of Rooted wools

### PR DESCRIPTION
**Pull request by Palmidence**

### CODE REVIEW

**Comment by Whnd** [comment]
pls dont

**Comment by HazryG** [comment]
I would suggest making it a number that's divisible by 100 so that the percentage on the sidebar looks normal :p

**Comment by Palmidence** [comment]
@Whnd 5 is too low for a DTW map in the first place :thinking:

**Comment by Whnd** [comment]
i like it to be 5 wools dont change it kthx

**Pull request merged**
