### PR TITLE
Add Hijacked

### PR DESCRIPTION
**Pull request by DeternoMC**
Hijacked is an infection map originated off Hijacked (call of duty black ops map)

### CODE REVIEW

**Comment by DeternoMC** [comment]
Don't mind the parts were I 'created a', 'deleted a' 'uploaded uid.dat', 'deleted uid.dat' this was my first time creating a pull request over github and had some issues, but i'm all cool with it now.

**Comment by tjhubz** [comment]
1. You need pictures
2. Did you edit the map from the original? If not, you cannot put yourself in the credits.

**Comment by DeternoMC** [comment]
@tjhubz I added pictures, and originally, I had about 3 spots created myself. However, I've edited it and added several more spots into the map. I believe there are 7/8/9 spots.

**Comment by tjhubz** [comment]
Post images in comments, not in map files

**Comment by DeternoMC** [comment]
Oh I see. 
[i.imgur.com/6R6h117.jpg](https://i.imgur.com/6R6h117.jpg)

**Comment by tjhubz** [comment]
Hm. We used to have this map but I don't think it is large enough for use on Warzone. Sorry.

**Pull request closed without merging**
