### PR TITLE
Chunky (WZ DTW Map)

### PR DESCRIPTION
**Pull request by JackJack33**
I think i successfully combined two different gamemodes that work together well. Shrug, you find out.

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
Could you provide us with some screenshots of the map here?

**Comment by JackJack33** [comment]
I was a little lazy with the visual appeal on this map, but i think the gameplay flows nicely. Its a classic DTW game, but with a key difference; there are "control points". These points are places on the map that give advantages when controlled by a team. There are three of them and they are marked by an impression with stone slabs in the middle.

**Comment by pdxryanpdx** [comment]
Maybe more detail?

**Comment by JackJack33** [comment]
ill see what i can add

**Comment by BennyDoesTheStuff** [comment]
Also, your JSON is a bit wrong, "DTW" is not a gamemode. The correct term you are looking for is "DTM"

**Comment by JackJack33** [comment]
working on it, thanks!

**Comment by JackJack33** [comment]
thoughts?

**Comment by JackJack33** [comment]
Updated map, opinions?

**Comment by Palmidence** [comment]
Looks better, but I'd add some floor designs to the "chunks". It looks really boring just one color, perhaps incorporate some of the other colors underneath as a part of the surface layer?

**Pull request closed without merging**
