### PR TITLE
Update map.json

### PR DESCRIPTION
**Pull request by PundaChen**
Add bow

### CODE REVIEW

**Comment by CrazyisCreeps** [comment]
This is a rage map, but the bow appears to be regular. The how should kill with one shot

**Comment by PundaChen** [comment]
Fixed, I hope

**Comment by CrazyisCreeps** [comment]
I'm going to hold off on merging this for now, as it does appear that other command blocks used on the map are also having issues. Could have been caused by the server updating to 1.14.

Probably makes sense to either fix the command blocks, or recreate everything in JSON. What do you think?

**Comment by PundaChen** [comment]
I have no idea what the function of the command blocks are in this map so I'm not sure how much you'd have to recreate.

**Comment by CrazyisCreeps** [comment]
Command blocks have changed so much in the last couple of years, not sure I know the difference between the colours. There's 10 total. From what I gather, it gives a damage 1000 bow. It also gives speed 2 and jump boost 2 on spawn. The command blocks also make the launch pads function, tracking when players are standing over them and giving a large amount of jump boost. Lastly, a sharpness 1000 sword is given

**Comment by CrazyisCreeps** [comment]
I figure all but the launch pads can be jsoned, makes more sense to have it here rather than reliant on some command blocks ingame

**Comment by PundaChen** [comment]
Oh damn, all I know that I can do is the swords and the bow (which is already in this pr.)

**Comment by CrazyisCreeps** [comment]
For the time being I guess, just to make it somewhat playable, do you want to add a sword to your pr and then I'll merge it?

**Comment by PundaChen** [comment]
I think the sword and bow should be working with this.

**Pull request merged**
