### PR TITLE
Update rotation.txt

### PR DESCRIPTION
**Pull request by Xounaut**
If you merge Atdits PR for Senex 3's name this will be fine, I also removed a map from the rotation

### CODE REVIEW

**Comment by R2nR2n** [comment]
It it’s the same thing as Atdit’s just close this pull request, no need to have it be duplicated.

**Comment by Xounaut** [comment]
No i removed a map, and atdit changed a name of a map which is the map that isn’t in the rot because of its name, so if you merge atditc PR the map will be added into the rot

**Comment by BennyDoesTheStuff** [comment]
No need for this. The Senex 3 and Cloudy Domain maps work just fine.

**Comment by Xounaut** [comment]
Cloudy domain is just a cancerous map to play on with so much bow spam, which is why i removed if lol

**Pull request closed without merging**
