### PR TITLE
how are people supposed to eat unbreakable apples (Quintus)

### PR DESCRIPTION
**Pull request by ThatOneTqnk**
unspecified image

### CODE REVIEW

**Comment by Owehttamy** [comment]
#297 Duplicate of mine get outta here

**Comment by ThatOneTqnk** [comment]
changes look different to me

**Comment by Owehttamy** [comment]
because you didn't make them unbreaking like every other map

**Comment by ThatOneTqnk** [comment]
that is indeed a difference therefore affirming that the changes do look different to me

**Comment by Owehttamy** [comment]
But they both solve the same issue.
   The thing is that my pull request is more similar to other maps as their golden apples have unbreaking as well.
   So, unless you would want to spend your time going through every map's json files *and* chests (because the golden apples in chests have unbreaking) then be my guest.
   And, in an unjokingly manner I'd prefer that I get credit for my fixes on map issues, not people who are just plagiarizing my efforts and trying to differ it in a way not only to spite me and my attempts to give the server some quality of life improvement but also then trying to make a joke arguement even though you knew what I meant.
   Spend your time on fixing the hit registration issues or some of the other 44 issues that are still sitting in the main plugin and let me do what I know how to. Thanks.

**Comment by ThatOneTqnk** [comment]
> But they both solve the same issue.
The thing is that my pull request is more similar to other maps as their golden apples have unbreaking as well. So, unless you would want to spend your time going through every map's json files and chests (because the golden apples in chests have unbreaking) then be my guest.

I do not believe it is a good idea to throw out a solution that is more fitting just because it would be cumbersome to execute the solution. You are implying that you are taking a shortcut, when there is a more fitting solution.

> And, in an unjokingly manner I'd prefer that I get credit for my fixes on map issues, not people who are just plagiarizing my efforts and trying to differ it in a way not only to spite me and my attempts to give the server some quality of life improvement...

I did not plagiarize your "efforts" at all. That's simply not how it works. There is a problem at hand and you proposed a solution. There was then a comment that explained why another solution would be more fitting, of which I decided to implement. Nowhere in that process does that imply any intent on my part to plagiarize you. The solutions are clearly different, they just solve the same problem. One removes unwanted behavior and the other one generalizes unwanted behavior (Hint: My solution is the one that removes the unwanted behavior). So the fact that my solution was "trying to differ in a way not only to spite me..." is objectively incorrect. 

> but also then trying to make a joke arguement even though you knew what I meant.

Even if you claim that it is a joke argument, nevertheless, it is valid. You essentially said: "well, you didn't do what every other map did," and I stated that, yes, that is what makes our solutions different, therefore, not a duplicate by definition.

> Spend your time on fixing the hit registration issues or some of the other 44 issues that are still sitting in the main plugin and let me do what I know how to. Thank

This is not related to the Maps repository at all. Why do you feel the need to bring this up? Clearly, that is out of the scope of this PR and should not be discussed here, I would like to hear your reasoning as to why you felt it was appropriate to include here since you seem it is appropriate.

You imply here that the 44 issues have to all be taken care of, but you fail to realize that the issues are also used as feature requests, not just bugs. If you also take approximately <20 seconds of your time to do some basic metrics, you will see that only 6 of the issues are bugs.

basic metrics that humans can do

**Comment by Owehttamy** [comment]
I brought up the main repository as it seems where Developers are needed most.
Features or not, they're still something that needs to be done anyways. Also one of those bugs is over a year old and hasn't been resolved.

If you attended the conversation in #mapmaking, after making my pull request a conversation sparked about the unbreaking golden apples. I stated that I would not be planning on converting every map any time soon as I just completed the itemremove modules with some of them not even been merged yet. Also I feel it would be a waste of my time to fix every map for one single item and not wait for a few issues or tweaks I could make so I could spend my time more efficiently.
You still have failed to point out why your pull request would be a better option or more fitting than mine even though mine fits closer to the other maps and how they were setup so later on when I do fix the maps Quintus will fit into the others the exact same way so I can do the same procedure to fix it.

If you really think all of this is necessary and that I can't roll out the tweaks and fixes in an efficient manner then you can go ahead and take care of it yourself.

**Comment by ThatOneTqnk** [comment]
> I brought up the main repository as it seems where Developers are needed most.
Once again, __objectively__ incorrect. That does not relate to this pull request at all.

> Features or not, they're still something that needs to be done anyways. Also one of those bugs is over a year old and hasn't been resolved.

You seem to be forgetting that other issues get taken care of. Those are the issues at the current time, as you may or may not know. I am not sure what your point here is, but if you are interested in gauging the activity of the plugin's development, there's this neat feature GitHub provides called the Insights tab. If you click on it and press the **Contributors** section, you will see a neat visual graph that shows commits over time.

it's a graph

As you may be able to tell, that means the commits have considerably gone up recently. 

It is also worth noting that this is all voluntary work, so there's no obligation to be fully devoted to a project like this.

> If you attended the conversation in #mapmaking, after making my pull request a conversation sparked about the unbreaking golden apples. I stated that I would not be planning on converting every map any time soon as I just completed the itemremove modules with some of them not even been merged yet. Also I feel it would be a waste of my time to fix every map for one single item and not wait for a few issues or tweaks I could make so I could spend my time more efficiently.

Seems you need a reality check. Who dictated that it was your responsibility to "convert any time soon"? You own no responsibility here. Your contributions are always appreciated, but you can't claim responsibility. The fact that you even imply that people contributing to this repository are somehow supposed to and should cater to your schedule of contribution is nonsensical and wrong.

> You still have failed to point out why your pull request would be a better option or more fitting than mine...

Fortunately, that is exactly what I did. I will edit the relevant text in the previous comment to be bold to mark emphasis.

> ...even though mine fits closer to the other maps and how they were setup...

Fortunately, I explained why this does not make your solution valid. Consistency does not equal validity.

> ...so later on when I do fix the maps Quintus will fit into the others the exact same way so I can do the same procedure to fix it.

Once again, there is assumption of responsibility here. Fortunately, I already explained why you are objectively wrong regarding this as well.

> If you really think all of this is necessary and that I can't roll out the tweaks and fixes in an efficient manner then you can go ahead and take care of it yourself.

Once again, it may be worthwhile to re-read my comment. Taking your shortcut generalizes unwanted behavior, my PR removes the unwanted behavior.

**Comment by Owehttamy** [comment]
> There is a problem at hand and you proposed a solution. There was then a comment that explained why another solution would be more fitting, of which I decided to implement.
It was a solution that I could've fixed on my commit within a few minutes maximum. But instead, you decided to add another pull request which in my opinion seemed unnecessary, as I was already participating in fixing a simple pull request.
> Seems you need a reality check. Who dictated that it was your responsibility to "convert any time soon"? You own no responsibility here. Your contributions are always appreciated, but you can't claim responsibility.
I worded that sloppily as it was already really late in the night, but I intended to say that I already started a conversation about attempting to fix the odd behavior and decisions by mapmakers on a later date and it would be more convenient fixing the issues if the majority of the maps had the same or similar problem so converting could be as simple as a copy and paste, rather than realizing the map is already acting in an intended manner. 
> Fortunately, I explained why this does not make your solution valid. Consistency does not equal validity.
Of course, it doesn't equal validity. But if we decided to remove this behavior without converting all of the maps it'd seem odd to remove the behavior from some specific maps that were made in the past, unless we're just going to slowly fix the maps' issues one-by-one or wherever we deem necessary but I'm not sure.

**Pull request closed without merging**
