### PR TITLE
Prevent wool room hopping on Desert Country

### PR DESCRIPTION
**Pull request by CrazyisCreeps**
Expanded regions in the correct direction and added extra barriers

### CODE REVIEW

**Comment by BennyDoesTheStuff** [comment]
One question I would have about the edit is if you pruned the map?

**Comment by CrazyisCreeps** [comment]
I didn't, so there might be some regions loaded in at 0 0 before I teleported to the map. If you're asking to make sure it's all still void, yes it is (I loaded it up to a build server to make the edits)

**Comment by BennyDoesTheStuff** [comment]
Yea, it seems like a good amount of void chunks got loaded in while you loaded it up.

LoadedChunks

**Comment by CrazyisCreeps** [comment]
Alright, I'll prune it later

**Comment by CrazyisCreeps** [comment]
Pruned.

**Pull request merged**
